on:
  issues:
    type: [labeled]

jobs:
  process_package_requests:
    runs-on: ubuntu-latest
    name: Add packages from open package requests
    container:
      image: gitcran/cflinuxfs3:r-4.0.2
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}
      - name: Install package dependencies
        #If your package has any dependecies you will need to install them in this step
        #run: sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable; sudo apt-get -y update; sudo apt-get -y install libgdal-dev libgeos-dev libproj-dev 
      - name: Run package addition pipeline in docker
        id: add_package_pipeline
        env:
          GITCRAN_REPO_OWNER: "testorg-2020"
          GITCRAN_REPO: "cflinuxfs3-CRAN"
          GITCRAN_FILTER_ORG: "testorg-2020"
          GITCRAN_SUBDIR: "cflinuxfs3"
          GITCRAN_LABELS: "package-request"
          GITCRAN_STATE: "open"
          GITHUB_USER: "${{ secrets.user }}"
          GITHUB_PAT: "${{ secrets.pat }}"
        run: |
          R -e "gitCRAN::package_request_pipeline()"
