on:
  issues:
    type: [labeled]
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  process_package_requests:
    runs-on: ubuntu-latest
    name: Add packages from open package requests
    defaults:
      run:
        working-directory: /workspace
    container:
      image: cloudfoundry/cflinuxfs3
      volumes: 
       - ${{ github.workspace }}:/workspace
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Turnstyle
        uses: softprops/turnstyle@v1
      - name: Install package dependencies
        run: |
          apt-get -y update
          apt-get install -y software-properties-common
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && \
          add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/' && \
          add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          apt-get -y update
          apt-get -y install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libnlopt-dev
                    export R_LIBS_USER=/opt/Rlib

          apt install -y r-base=4.1.3-1.1804.0 && \
          mkdir -p $R_LIBS_USER
      - name: Check install
        run: echo "$LD_LIBRARY_PATH"
      - name: Run package addition pipeline in docker
        id: add_package_pipeline
        env:
          GITCRAN_REPO_OWNER: "USEPA"
          GITCRAN_REPO: "cflinuxfs3-CRAN"
          GITCRAN_FILTER_ORG: "USEPA"
          GITCRAN_SUBDIR: "cflinuxfs3"
          GITCRAN_LABELS: "package-request"
          GITCRAN_STATE: "open"
          GITHUB_USER: "github-actions"
        run: |
          R -e "install.packages('devtools', repos = 'cloud.r-project.org')"
          R -e "devtools::install_local('CRANpiled')"
          R -e "devtools::install_local('gitCRAN')"

          R -e "gitCRAN::package_request_pipeline()"
