on:
  issues:
    type: [labeled]
  workflow_dispatch:
    inputs:
      package_requests:
        description: 'Packages to add'

permissions:
  contents: write
  issues: write

jobs:
  process_package_requests:
    runs-on: ubuntu-latest
    name: Add packages from open package requests
    defaults:
      run:
        working-directory: /workspace
    container:
      image: cloudfoundry/cflinuxfs3
      volumes:
       - ${{ github.workspace }}:/workspace
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1

      - name: Install package dependencies
        run: |
          apt-get -y update
          apt-get install -y software-properties-common
          apt-get -y install git
          git config --global --add safe.directory /__w/cflinuxfs3-CRAN/cflinuxfs3-CRAN

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Get R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            devtools
            rgdal
            sp
            sf
            rgeos
            
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check install
        run: |
          echo "$LD_LIBRARY_PATH"
          git --version

      - name: Install local packages
        run: |
          R -e "devtools::install_local('CRANpiled')"
          R -e "devtools::install_local('gitCRAN')"

      - name: Run package addition pipeline in docker
        id: add_package_pipeline
        env:
          GITCRAN_REPO_OWNER: "USEPA"
          GITCRAN_REPO: "cflinuxfs3-CRAN"
          GITCRAN_FILTER_ORG: "USEPA"
          GITCRAN_SUBDIR: "cflinuxfs3"
          GITCRAN_LABELS: "package-request"
          GITCRAN_STATE: "open"
          GITHUB_USER: "github-actions"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: R -e "gitCRAN::package_request_pipeline('${{ github.event.inputs.package_requests }}')"
